In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("world_economics.csv")
df

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Tunisia,Tunisian dinar,Tunis,Arabic,34.000000,9.000000,163610.0,Africa,Northern Africa,"['DZA', 'LBY']",53,1.80,7.50,5.30,15.70,-6.6,79.8,-2.7,11.89
1,Vietnam,Vietnamese đồng,Hanoi,Vietnamese,16.166667,107.833333,331212.0,Asia,South-Eastern Asia,"['KHM', 'CHN', 'LAO']",476,6.88,4.50,3.19,2.24,-4.0,32.9,6.1,101.30
2,Ecuador,United States dollar,Quito,Spanish,-2.000000,-77.500000,276841.0,Americas,South America,"['COL', 'PER']",125,3.46,8.50,0.72,4.50,-1.9,50.6,2.8,17.97
3,Puerto Rico,United States dollar,San Juan,English,18.250000,-66.500000,8870.0,Americas,Caribbean,NaN,126,NaN,NaN,1.20,5.70,NaN,NaN,NaN,3.20
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,3.00,4.50,2.70,4.20,-6.4,124.3,-3.9,341.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,New Caledonia,CFP franc,Nouméa,French,-21.500000,165.500000,18575.0,Oceania,Melanesia,NaN,10,NaN,2.00,0.80,11.20,NaN,NaN,NaN,0.29
169,Kosovo,Euro,Pristina,Albanian,42.666667,21.166667,10908.0,Europe,Southeast Europe,"['ALB', 'MKD', 'MNE', 'SRB']",11,NaN,NaN,4.30,10.80,0.2,16.9,-9.0,1.60
170,Malaysia,Malaysian ringgit,Kuala Lumpur,English,2.500000,112.500000,330803.0,Asia,South-Eastern Asia,"['BRN', 'IDN', 'THA']",422,2.10,2.75,1.20,3.00,-4.1,70.4,1.7,34.10
171,Fiji,Fijian dollar,Suva,English,-17.713400,178.065000,18272.0,Oceania,Melanesia,NaN,6,NaN,0.25,-0.40,4.30,-3.4,78.3,-8.7,0.93
172,Jamaica,Jamaican dollar,Kingston,English,18.250000,-77.500000,10991.0,Americas,Caribbean,NaN,20,0.80,5.75,3.30,3.30,-1.0,67.9,1.3,2.82

In [3]:
df.columns

Index(['name', 'currency', 'capital', 'languages', 'latitude', 'longitude',
       'area', 'region', 'subregion', 'borders', 'GDP', 'GDP Growth',
       'Interest Rate', 'Inflation Rate', 'Jobless Rate', 'Gov. Budget',
       'Debt/GDP', 'Current Account', 'Population'],
      dtype='object')

#### interst rate=>the central bank policy interest rate
#### GDP=>total monetary value of all goods and services produced within a country in a specific period
#### inflation Rate=> percentage increase in the average price level of goods and services in a country over a certain period of time
#### GDP Growth=>percentage change in a country’s GDP compared to a previous period
#### Debt/GDP=> measures a country’s government debt compared to the size of its economy (GDP).
#### Current Account=> measures the flow of goods, services, income, and transfers between a country and the rest of the world.

In [4]:
df.head()

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Tunisia,Tunisian dinar,Tunis,Arabic,34.000000,9.000000,163610.0,Africa,Northern Africa,"['DZA', 'LBY']",53,1.80,7.5,5.30,15.70,-6.6,79.8,-2.7,11.89
1,Vietnam,Vietnamese đồng,Hanoi,Vietnamese,16.166667,107.833333,331212.0,Asia,South-Eastern Asia,"['KHM', 'CHN', 'LAO']",476,6.88,4.5,3.19,2.24,-4.0,32.9,6.1,101.30
2,Ecuador,United States dollar,Quito,Spanish,-2.000000,-77.500000,276841.0,Americas,South America,"['COL', 'PER']",125,3.46,8.5,0.72,4.50,-1.9,50.6,2.8,17.97
3,Puerto Rico,United States dollar,San Juan,English,18.250000,-66.500000,8870.0,Americas,Caribbean,NaN,126,NaN,NaN,1.20,5.70,NaN,NaN,NaN,3.20
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,3.00,4.5,2.70,4.20,-6.4,124.3,-3.9,341.15

In [5]:
df.tail()

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
168,New Caledonia,CFP franc,Nouméa,French,-21.500000,165.500000,18575.0,Oceania,Melanesia,NaN,10,NaN,2.00,0.8,11.2,NaN,NaN,NaN,0.29
169,Kosovo,Euro,Pristina,Albanian,42.666667,21.166667,10908.0,Europe,Southeast Europe,"['ALB', 'MKD', 'MNE', 'SRB']",11,NaN,NaN,4.3,10.8,0.2,16.9,-9.0,1.60
170,Malaysia,Malaysian ringgit,Kuala Lumpur,English,2.500000,112.500000,330803.0,Asia,South-Eastern Asia,"['BRN', 'IDN', 'THA']",422,2.1,2.75,1.2,3.0,-4.1,70.4,1.7,34.10
171,Fiji,Fijian dollar,Suva,English,-17.713400,178.065000,18272.0,Oceania,Melanesia,NaN,6,NaN,0.25,-0.4,4.3,-3.4,78.3,-8.7,0.93
172,Jamaica,Jamaican dollar,Kingston,English,18.250000,-77.500000,10991.0,Americas,Caribbean,NaN,20,0.8,5.75,3.3,3.3,-1.0,67.9,1.3,2.82

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          172 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       101 non-null    float64
 12  Interest Rate    162 non-null    float64
 13  Inflation Rate   172 non-null    float64
 14  Jobless Rate     171 non-null    float64
 15  Gov. Budget      166 non-null    float64
 16  Debt/GDP         165 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

### Missing value
- GDP Growth 
- Interest Rate    
- Inflation Rate  
- Jobless Rate     
- Gov. Budget      
- Debt/GDP         
- Current Account

In [7]:
df.describe()

,latitude,longitude,area,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
count,173.000000,173.000000,1.730000e+02,173.000000,101.000000,162.000000,172.000000,171.000000,166.000000,165.000000,167.000000,173.000000
mean,20.437142,22.371774,7.561437e+05,637.508671,1.115644,7.802222,8.348663,7.363099,-2.822831,60.945879,-0.545269,45.570058
std,23.961270,58.849734,2.007481e+06,2703.930867,3.820764,8.169314,21.367006,6.065999,4.265735,38.998840,8.871213,155.896870
min,-41.000000,-102.000000,2.020000e+00,2.000000,-23.700000,0.000000,-9.100000,0.100000,-17.600000,2.300000,-31.500000,0.040000
25%,6.500000,-2.000000,3.839400e+04,20.000000,0.100000,2.812500,1.275000,3.200000,-4.975000,36.100000,-4.900000,3.540000
50%,20.000000,24.000000,1.810350e+05,72.000000,0.700000,5.250000,3.350000,5.200000,-3.175000,54.900000,-1.000000,10.580000
75%,40.000000,49.000000,5.870410e+05,373.000000,1.800000,9.187500,5.300000,9.115000,-1.100000,76.500000,3.210000,34.430000
max,65.000000,178.065000,1.709824e+07,29185.000000,18.600000,59.230000,172.000000,33.200000,21.600000,272.000000,31.400000,1408.000000

In [8]:
df["GDP Growth"].isna().sum()

np.int64(72)

In [9]:
x=df[df["GDP Growth"].isna()]
x["name"].unique()

array(['Puerto Rico', 'Myanmar', 'Afghanistan', 'Bhutan', 'Nepal', 'Iraq',
       'Sudan', 'Djibouti', 'Liechtenstein', 'Burundi', 'Jordan',
       'Equatorial Guinea', 'Kyrgyzstan', 'Mauritania', 'Malawi',
       'Panama', 'Georgia', 'Armenia', 'South Sudan', 'Iran', 'Somalia',
       'Guyana', 'Niger', 'Republic of the Congo', 'Ivory Coast',
       'Maldives', 'Mali', 'Laos', 'Zimbabwe', 'Turkmenistan', 'Cuba',
       'Benin', 'Uzbekistan', 'Chad', 'Syria', 'Burkina Faso', 'Togo',
       'Cambodia', 'Comoros', 'Ethiopia', 'Tajikistan', 'Gambia',
       'Liberia', 'Guatemala', 'Sierra Leone', 'Monaco', 'Lebanon',
       'Seychelles', 'Zambia', 'Suriname', 'Eritrea', 'Papua New Guinea',
       'Montenegro', 'Libya', 'Guinea', 'Brunei', 'Madagascar',
       'Azerbaijan', 'Palestine', 'Central African Republic', 'Nicaragua',
       'Bahamas', 'Oman', 'Belarus', 'Yemen', 'Haiti', 'Cayman Islands',
       'Gabon', 'Macau', 'New Caledonia', 'Kosovo', 'Fiji'], dtype=object)

# Scrab data from Wikipedia

In [10]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_countries_by_real_GDP_growth_rate"

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
tables = pd.read_html(response.text)

print(len(tables))   
GDP_Gr = tables[1]    
GDP_Gr.columns = ["name", "GDP Growth"]
GDP_Gr.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_21404\3227627432.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

8

,name,GDP Growth
0,Growth by country Country Rate (%) Albania 3....,Growth by region Region Rate (%) Africa 3.2 As...
1,Country,Rate (%)
2,Albania,3.8
3,Algeria,3.5
4,Andorra,1.9

In [11]:
GDP_Gr2=df[["name","GDP Growth"]]
GDP_Gr2

              name  GDP Growth
0          Tunisia        1.80
1          Vietnam        6.88
2          Ecuador        3.46
3      Puerto Rico         NaN
4    United States        3.00
..             ...         ...
168  New Caledonia         NaN
169         Kosovo         NaN
170       Malaysia        2.10
171           Fiji         NaN
172        Jamaica        0.80

[173 rows x 2 columns]

In [12]:
GDP_Gr3=GDP_Gr.iloc[2:]
GDP_Gr3

                              name GDP Growth
2                          Albania        3.8
3                          Algeria        3.5
4                          Andorra        1.9
5                           Angola        2.4
6              Antigua and Barbuda        3.0
..                             ...        ...
221  Major advanced economies (G7)        1.5
222   Middle East and Central Asia        2.0
223       Other advanced economies        1.8
224             Sub-Saharan Africa        3.3
225                          World        3.0

[224 rows x 2 columns]

In [13]:
GDP_Gr3 = GDP_Gr3[GDP_Gr3["GDP Growth"] != "Rate (%)"]

In [14]:
GDP_Gr3["GDP Growth"] = GDP_Gr3["GDP Growth"].str.replace("−", "-", regex=True)
GDP_Gr3["GDP Growth"]=GDP_Gr3["GDP Growth"].astype(float)

C:\Users\HP\AppData\Local\Temp\ipykernel_21404\2115179841.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GDP_Gr3["GDP Growth"] = GDP_Gr3["GDP Growth"].str.replace("−", "-", regex=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_21404\2115179841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GDP_Gr3["GDP Growth"]=GDP_Gr3["GDP Growth"].astype(float)

In [15]:

GDP_Gr3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 223 entries, 2 to 225
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        223 non-null    object
 1   GDP Growth  223 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.2+ KB

In [17]:
GDP_Gr4=pd.merge(GDP_Gr2,GDP_Gr3,on="name",how="left")
GDP_Gr4

              name  GDP Growth_x  GDP Growth_y
0          Tunisia          1.80           1.4
1          Vietnam          6.88           6.1
2          Ecuador          3.46           1.7
3      Puerto Rico           NaN          -0.8
4    United States          3.00           1.8
..             ...           ...           ...
168  New Caledonia           NaN           NaN
169         Kosovo           NaN           4.0
170       Malaysia          2.10           4.1
171           Fiji           NaN           2.6
172        Jamaica          0.80           2.1

[173 rows x 3 columns]

In [20]:
GDP_Gr4.drop(columns=["GDP Growth_x"],inplace=True)

In [21]:
GDP_Gr4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          173 non-null    object
 1   GDP Growth_y  160 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.8+ KB

In [22]:
GDP_Gr4.head()

            name  GDP Growth_y
0        Tunisia           1.4
1        Vietnam           6.1
2        Ecuador           1.7
3    Puerto Rico          -0.8
4  United States           1.8

In [23]:
GDP_Gr2.head()

            name  GDP Growth
0        Tunisia        1.80
1        Vietnam        6.88
2        Ecuador        3.46
3    Puerto Rico         NaN
4  United States        3.00

In [24]:
df["GDP Growth"]=GDP_Gr4["GDP Growth_y"]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          172 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       160 non-null    float64
 12  Interest Rate    162 non-null    float64
 13  Inflation Rate   172 non-null    float64
 14  Jobless Rate     171 non-null    float64
 15  Gov. Budget      166 non-null    float64
 16  Debt/GDP         165 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [26]:
x=df[df["GDP Growth"].isna()]
x["name"].unique()

array(['Afghanistan', 'Liechtenstein', 'Cuba', 'Slovakia', 'Cape Verde',
       'Syria', 'Monaco', 'Lebanon', 'Eritrea', 'Palestine',
       'Cayman Islands', 'Macau', 'New Caledonia'], dtype=object)

# from many resourses having GDP_Growth

In [27]:
gdp_growth = {
    "Afghanistan": 2.71,        
    "Cuba": -1.90,              
    "Monaco": 5.0,              
    "Liechtenstein": 0.5,      
    "Slovakia": 0.2,
    "Cape Verde": 5.9,
    "Syria": 1.30,
    "Lebanon": -5.00,
    "Eritrea": 2.80,
    "Palestine":  9.1,
    "Cayman Islands": 3.50,
    "Macau": 5.1,
    "New Caledonia": 1.20
}

In [28]:
df["GDP Growth"]=df["GDP Growth"].fillna(df["name"].map(gdp_growth))

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          172 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    162 non-null    float64
 13  Inflation Rate   172 non-null    float64
 14  Jobless Rate     171 non-null    float64
 15  Gov. Budget      166 non-null    float64
 16  Debt/GDP         165 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [30]:
x=df[df["Interest Rate"].isna()]
x["name"].unique()

array(['Puerto Rico', 'Liechtenstein', 'Somalia', 'Turkmenistan', 'Syria',
       'Monaco', 'Eritrea', 'Montenegro', 'Palestine', 'Cayman Islands',
       'Kosovo'], dtype=object)

# non known=-100

In [31]:
interest_rates = {
    "Puerto Rico": 6.60,       
    "Liechtenstein": 1.75,    
    "Somalia": -21.3,           
    "Turkmenistan": -100,      
    "Syria": -100,            
    "Monaco": -100,            
    "Eritrea": -100,          
    "Montenegro": 6.6,       
    "Palestine": -3.12,         
    "Cayman Islands": -100,    
    "Kosovo": 2.90             
}

In [32]:
df["Interest Rate"]=df["Interest Rate"].fillna(df["name"].map(interest_rates))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          172 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    173 non-null    float64
 13  Inflation Rate   172 non-null    float64
 14  Jobless Rate     171 non-null    float64
 15  Gov. Budget      166 non-null    float64
 16  Debt/GDP         165 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [33]:
x=df[df["Inflation Rate"].isna()]
x["name"].unique()

array(['Monaco'], dtype=object)

In [34]:
df.loc[df["name"] == "Monaco", "Inflation Rate"] = 5.303

In [35]:
x=df[df["Jobless Rate"].isna()]
x["name"].unique()

array(['Somalia', 'Monaco'], dtype=object)

In [36]:
df.loc[df["name"] == "Somalia", "Jobless Rate"] = 18.86
df.loc[df["name"] == "Monaco", "Jobless Rate"] = 0.00

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          172 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    173 non-null    float64
 13  Inflation Rate   173 non-null    float64
 14  Jobless Rate     173 non-null    float64
 15  Gov. Budget      166 non-null    float64
 16  Debt/GDP         165 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [38]:
x=df[df["capital"].isna()]
x["name"].unique()

array(['Macau'], dtype=object)

In [39]:
df.loc[df["name"] == "Macau", "capital"] = "No Capital"

In [40]:
x=df[df["Gov. Budget"].isna()]
x["name"].unique()

array(['Puerto Rico', 'Liechtenstein', 'South Sudan', 'Somalia', 'Monaco',
       'Macau', 'New Caledonia'], dtype=object)

In [41]:
df

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Tunisia,Tunisian dinar,Tunis,Arabic,34.000000,9.000000,163610.0,Africa,Northern Africa,"['DZA', 'LBY']",53,1.4,7.50,5.30,15.70,-6.6,79.8,-2.7,11.89
1,Vietnam,Vietnamese đồng,Hanoi,Vietnamese,16.166667,107.833333,331212.0,Asia,South-Eastern Asia,"['KHM', 'CHN', 'LAO']",476,6.1,4.50,3.19,2.24,-4.0,32.9,6.1,101.30
2,Ecuador,United States dollar,Quito,Spanish,-2.000000,-77.500000,276841.0,Americas,South America,"['COL', 'PER']",125,1.7,8.50,0.72,4.50,-1.9,50.6,2.8,17.97
3,Puerto Rico,United States dollar,San Juan,English,18.250000,-66.500000,8870.0,Americas,Caribbean,NaN,126,-0.8,6.60,1.20,5.70,NaN,NaN,NaN,3.20
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,1.8,4.50,2.70,4.20,-6.4,124.3,-3.9,341.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,New Caledonia,CFP franc,Nouméa,French,-21.500000,165.500000,18575.0,Oceania,Melanesia,NaN,10,1.2,2.00,0.80,11.20,NaN,NaN,NaN,0.29
169,Kosovo,Euro,Pristina,Albanian,42.666667,21.166667,10908.0,Europe,Southeast Europe,"['ALB', 'MKD', 'MNE', 'SRB']",11,4.0,2.90,4.30,10.80,0.2,16.9,-9.0,1.60
170,Malaysia,Malaysian ringgit,Kuala Lumpur,English,2.500000,112.500000,330803.0,Asia,South-Eastern Asia,"['BRN', 'IDN', 'THA']",422,4.1,2.75,1.20,3.00,-4.1,70.4,1.7,34.10
171,Fiji,Fijian dollar,Suva,English,-17.713400,178.065000,18272.0,Oceania,Melanesia,NaN,6,2.6,0.25,-0.40,4.30,-3.4,78.3,-8.7,0.93
172,Jamaica,Jamaican dollar,Kingston,English,18.250000,-77.500000,10991.0,Americas,Caribbean,NaN,20,2.1,5.75,3.30,3.30,-1.0,67.9,1.3,2.82

In [42]:
gov_budget_balance = {
    "Puerto Rico": -100,        
    "Liechtenstein": 0.6,       
    "South Sudan": -4.0,        
    "Somalia": -100,            
    "Monaco": -0.5,            
    "Macau": -1.0,              
    "New Caledonia": -0.1       
}
df["Gov. Budget"]=df["Gov. Budget"].fillna(df["name"].map(gov_budget_balance))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          173 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    173 non-null    float64
 13  Inflation Rate   173 non-null    float64
 14  Jobless Rate     173 non-null    float64
 15  Gov. Budget      173 non-null    float64
 16  Debt/GDP         165 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [43]:
x=df[df["Debt/GDP"].isna()]
x["name"].unique()

array(['Puerto Rico', 'Liechtenstein', 'South Sudan', 'Somalia', 'Mali',
       'Monaco', 'Macau', 'New Caledonia'], dtype=object)

# Unknown=-10000

In [44]:
debt_to_gdp = {
    "Puerto Rico": 47.0,
    "Liechtenstein": 0.5,
    "South Sudan": 54.32,
    "Somalia": 77.0,
    "Mali": 51.88,
    "Monaco": -10000,
    "Macau": 0,
    "New Caledonia": 0
}

In [45]:
df["Debt/GDP"]=df["Debt/GDP"].fillna(df["name"].map(debt_to_gdp))

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          173 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    173 non-null    float64
 13  Inflation Rate   173 non-null    float64
 14  Jobless Rate     173 non-null    float64
 15  Gov. Budget      173 non-null    float64
 16  Debt/GDP         173 non-null    float64
 17  Current Account  167 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [47]:
x=df[df["Current Account"].isna()]
x["name"].unique()

array(['Puerto Rico', 'Liechtenstein', 'South Sudan', 'Somalia', 'Monaco',
       'New Caledonia'], dtype=object)

# Unknown=-1000

In [48]:
current_account = {
    "Puerto Rico": 4.9,
    "Liechtenstein": -1000,#Unknown
    "South Sudan": 13.61,
    "Somalia": -12.4,
    "Monaco": -1000,
    "New Caledonia": -1000#Unknown
}
df["Current Account"]=df["Current Account"].fillna(df["name"].map(current_account))

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          173 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          149 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    173 non-null    float64
 13  Inflation Rate   173 non-null    float64
 14  Jobless Rate     173 non-null    float64
 15  Gov. Budget      173 non-null    float64
 16  Debt/GDP         173 non-null    float64
 17  Current Account  173 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [50]:
df.head()

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Tunisia,Tunisian dinar,Tunis,Arabic,34.000000,9.000000,163610.0,Africa,Northern Africa,"['DZA', 'LBY']",53,1.4,7.5,5.30,15.70,-6.6,79.8,-2.7,11.89
1,Vietnam,Vietnamese đồng,Hanoi,Vietnamese,16.166667,107.833333,331212.0,Asia,South-Eastern Asia,"['KHM', 'CHN', 'LAO']",476,6.1,4.5,3.19,2.24,-4.0,32.9,6.1,101.30
2,Ecuador,United States dollar,Quito,Spanish,-2.000000,-77.500000,276841.0,Americas,South America,"['COL', 'PER']",125,1.7,8.5,0.72,4.50,-1.9,50.6,2.8,17.97
3,Puerto Rico,United States dollar,San Juan,English,18.250000,-66.500000,8870.0,Americas,Caribbean,NaN,126,-0.8,6.6,1.20,5.70,-100.0,47.0,4.9,3.20
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,1.8,4.5,2.70,4.20,-6.4,124.3,-3.9,341.15

In [51]:
x=df[df["borders"].isna()]
x["name"].unique()

array(['Puerto Rico', 'Malta', 'Philippines', 'New Zealand', 'Maldives',
       'Cuba', 'Mauritius', 'Cape Verde', 'Taiwan', 'Comoros', 'Cyprus',
       'Singapore', 'Seychelles', 'Madagascar', 'Bahrain', 'Australia',
       'Bahamas', 'Iceland', 'Japan', 'Cayman Islands',
       'Trinidad and Tobago', 'New Caledonia', 'Fiji', 'Jamaica'],
      dtype=object)

In [52]:
df.loc[df["name"] == "Cyprus", "borders"] = "GBR"
df.loc[df["name"] == "Singapore", "borders"] = "MYS"

In [53]:
df["borders"].fillna("NO BORDER")

0                    ['DZA', 'LBY']
1             ['KHM', 'CHN', 'LAO']
2                    ['COL', 'PER']
3                         NO BORDER
4                    ['CAN', 'MEX']
                   ...
168                       NO BORDER
169    ['ALB', 'MKD', 'MNE', 'SRB']
170           ['BRN', 'IDN', 'THA']
171                       NO BORDER
172                       NO BORDER
Name: borders, Length: 173, dtype: object

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             173 non-null    object
 1   currency         173 non-null    object
 2   capital          173 non-null    object
 3   languages        173 non-null    object
 4   latitude         173 non-null    float64
 5   longitude        173 non-null    float64
 6   area             173 non-null    float64
 7   region           173 non-null    object
 8   subregion        173 non-null    object
 9   borders          151 non-null    object
 10  GDP              173 non-null    int64
 11  GDP Growth       173 non-null    float64
 12  Interest Rate    173 non-null    float64
 13  Inflation Rate   173 non-null    float64
 14  Jobless Rate     173 non-null    float64
 15  Gov. Budget      173 non-null    float64
 16  Debt/GDP         173 non-null    float64
 17  Current Account  173 non-null    float64
 18  Population       173 non-null    float64
dtypes: float64(11), int64(1), object(7)
memory usage: 25.8+ KB

In [56]:
df.columns

Index(['name', 'currency', 'capital', 'languages', 'latitude', 'longitude',
       'area', 'region', 'subregion', 'borders', 'GDP', 'GDP Growth',
       'Interest Rate', 'Inflation Rate', 'Jobless Rate', 'Gov. Budget',
       'Debt/GDP', 'Current Account', 'Population'],
      dtype='object')

In [59]:
df.describe()

,latitude,longitude,area,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
count,173.000000,173.000000,1.730000e+02,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000
mean,20.437142,22.371774,7.561437e+05,637.508671,3.328960,4.377977,8.331058,7.386994,-3.893584,1.657630,-17.832081,45.570058
std,23.961270,58.849734,2.007481e+06,2703.930867,3.242023,19.861826,21.306060,6.119770,11.237425,765.823809,131.150223,155.896870
min,-41.000000,-102.000000,2.020000e+00,2.000000,-5.000000,-100.000000,-9.100000,0.000000,-100.000000,-10000.000000,-1000.000000,0.040000
25%,6.500000,-2.000000,3.839400e+04,20.000000,1.800000,2.250000,1.300000,3.200000,-5.000000,35.000000,-5.300000,3.540000
50%,20.000000,24.000000,1.810350e+05,72.000000,2.800000,5.100000,3.400000,5.200000,-3.150000,54.320000,-1.000000,10.580000
75%,40.000000,49.000000,5.870410e+05,373.000000,4.400000,8.500000,5.300000,9.130000,-1.010000,74.180000,3.220000,34.430000
max,65.000000,178.065000,1.709824e+07,29185.000000,27.200000,59.230000,172.000000,33.200000,21.600000,272.000000,31.400000,1408.000000

In [65]:
Q3=34.430000
IQR=34.430000-3.540000
Upper=34.430000 +1.5*IQR
high_population=df[df["Population"]>Upper]
high_population

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
1,Vietnam,Vietnamese đồng,Hanoi,Vietnamese,16.166667,107.833333,331212.0,Asia,South-Eastern Asia,"['KHM', 'CHN', 'LAO']",476,6.1,4.50,3.19,2.24,-4.0,32.90,6.10,101.30
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,1.8,4.50,2.70,4.20,-6.4,124.30,-3.90,341.15
14,Russia,Russian ruble,Moscow,Russian,60.000000,100.000000,17098242.0,Europe,Eastern Europe,"['AZE', 'BLR', 'CHN', 'EST', 'FIN', 'GEO', 'KA...",2174,1.5,18.00,8.80,2.20,-1.7,16.40,2.90,146.20
33,Turkey,Turkish lira,Ankara,Turkish,39.000000,35.000000,783562.0,Asia,Western Asia,"['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IR...",1323,2.7,43.00,33.52,8.60,-4.9,24.70,-0.80,85.67
34,Philippines,Philippine peso,Manila,English,13.000000,122.000000,342353.0,Asia,South-Eastern Asia,NaN,462,6.1,5.25,0.90,3.70,-5.7,60.70,-3.80,112.90
43,Iran,Iranian rial,Tehran,Persian (Farsi),32.000000,53.000000,1648195.0,Asia,Southern Asia,"['AFG', 'ARM', 'AZE', 'IRQ', 'PAK', 'TUR', 'TKM']",437,0.3,23.00,38.70,7.20,-5.5,36.80,2.90,86.00
49,India,Indian rupee,New Delhi,English,20.000000,77.000000,3287590.0,Asia,Southern Asia,"['BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK']",3913,7.8,5.50,1.55,5.20,-4.8,81.59,-0.60,1398.60
77,Bangladesh,Bangladeshi taka,Dhaka,Bengali,24.000000,90.000000,147570.0,Asia,Southern Asia,"['MMR', 'IND']",450,3.8,10.00,8.55,4.70,-4.6,31.70,-1.40,171.60
86,Brazil,Brazilian real,Brasília,Portuguese,-10.000000,-55.000000,8515767.0,Americas,South America,"['ARG', 'BOL', 'COL', 'GUF', 'GUY', 'PRY', 'PE...",2179,2.7,15.00,5.23,5.80,-8.5,76.50,-2.55,212.58
94,Indonesia,Indonesian rupiah,Jakarta,Indonesian,-5.000000,120.000000,1904569.0,Asia,South-Eastern Asia,"['TLS', 'MYS', 'PNG']",1396,4.7,5.00,2.37,4.76,-2.3,38.80,-0.63,281.60
100,Ethiopia,Ethiopian birr,Addis Ababa,Amharic,8.000000,38.000000,1104300.0,Africa,Eastern Africa,"['DJI', 'ERI', 'KEN', 'SOM', 'SSD', 'SDN']",164,6.5,15.00,13.70,18.90,-2.0,32.00,-3.40,132.06
104,Nigeria,Nigerian naira,Abuja,English,10.000000,8.000000,923768.0,Africa,Western Africa,"['BEN', 'CMR', 'TCD', 'NER']",188,3.0,27.50,21.88,4.30,-6.1,52.90,-0.50,232.68
108,China,Chinese yuan,Beijing,Chinese,35.000000,105.000000,9706961.0,Asia,Eastern Asia,"['AFG', 'BTN', 'MMR', 'HKG', 'IND', 'KAZ', 'NP...",18744,4.0,3.00,0.00,5.20,-6.5,88.30,2.20,1408.00
124,Germany,Euro,Berlin,German,51.000000,9.000000,357114.0,Europe,Western Europe,"['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'LUX', 'NL...",4660,0.0,2.15,2.00,6.30,-2.8,62.50,5.70,83.60
132,Pakistan,Pakistani rupee,Islamabad,English,30.000000,70.000000,881912.0,Asia,Southern Asia,"['AFG', 'CHN', 'IND', 'IRN']",373,2.6,11.00,4.10,5.50,-6.8,80.00,-0.50,251.27
152,Japan,Japanese yen,Tokyo,Japanese,36.000000,138.000000,377930.0,Asia,Eastern Asia,NaN,4026,0.6,0.50,3.10,2.50,-2.3,236.70,4.70,120.65
159,Egypt,Egyptian pound,Cairo,Arabic,27.000000,30.000000,1002450.0,Africa,Northern Africa,"['ISR', 'LBY', 'PSE', 'SDN']",389,3.8,24.00,13.90,6.10,-7.1,82.90,-5.30,107.20
167,Mexico,Mexican peso,Mexico City,Spanish,23.000000,-102.000000,1964375.0,Americas,North America,"['BLZ', 'GTM', 'USA']",1853,-0.3,7.75,3.51,2.70,-5.7,49.70,-0.80,130.86

In [64]:
Q3=9.130000
IQR=9.130000-3.200000	
Upper1=9.130000 +1.5*IQR
Jobless=df[df["Jobless Rate"]>Upper1]
Jobless

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
11,Angola,Angolan kwanza,Luanda,Portuguese,-12.50,18.50,1246700.0,Africa,Middle Africa,"['COG', 'COD', 'ZMB', 'NAM']",80,2.4,19.50,19.48,29.40,-1.5,58.2,5.4,35.12
17,Sudan,Sudanese pound,Khartoum,Arabic,15.00,30.00,1886068.0,Africa,Northern Africa,"['CAF', 'TCD', 'EGY', 'ERI', 'ETH', 'LBY', 'SSD']",50,8.3,28.30,146.60,20.80,-3.2,272.0,-5.5,50.45
18,Djibouti,Djiboutian franc,Djibouti,Arabic,11.50,43.00,23200.0,Africa,Eastern Africa,"['ERI', 'ETH', 'SOM']",4,6.0,11.20,-0.60,25.90,-0.5,45.0,6.2,1.17
19,Mozambique,Mozambican metical,Maputo,Portuguese,-18.25,35.00,801590.0,Africa,Eastern Africa,"['MWI', 'ZAF', 'SWZ', 'TZA', 'ZMB', 'ZWE']",22,2.5,10.25,3.96,25.04,-5.0,76.9,-11.1,33.24
20,South Africa,South African rand,Pretoria,Afrikaans,-29.00,24.00,1221037.0,Africa,Southern Africa,"['BWA', 'LSO', 'MOZ', 'NAM', 'SWZ', 'ZWE']",400,1.0,7.00,3.50,33.20,-5.0,76.9,-0.6,63.02
25,Jordan,Jordanian dinar,Amman,Arabic,31.00,36.00,89342.0,Asia,Western Asia,"['IRQ', 'ISR', 'PSE', 'SAU', 'SYR']",53,2.6,6.50,1.68,21.30,-5.3,90.2,-5.0,11.73
47,Somalia,Somali shilling,Mogadishu,Arabic,10.00,49.00,637657.0,Africa,Eastern Africa,"['DJI', 'ETH', 'KEN']",12,4.0,-21.30,4.40,18.86,-100.0,77.0,-12.4,19.01
51,Republic of the Congo,Central African CFA franc,Brazzaville,French,-1.00,15.00,342000.0,Africa,Middle Africa,"['AGO', 'CMR', 'CAF', 'COD', 'GAB']",16,3.3,4.50,5.00,19.80,2.7,95.4,2.4,6.33
83,Senegal,West African CFA franc,Dakar,French,14.00,-14.00,196722.0,Africa,Western Africa,"['GMB', 'GIN', 'GNB', 'MLI', 'MRT']",32,9.3,5.25,1.80,21.70,-11.7,56.1,-12.1,18.80
100,Ethiopia,Ethiopian birr,Addis Ababa,Amharic,8.00,38.00,1104300.0,Africa,Eastern Africa,"['DJI', 'ERI', 'KEN', 'SOM', 'SSD', 'SDN']",164,6.5,15.00,13.70,18.90,-2.0,32.0,-3.4,132.06
102,Botswana,Botswana pula,Gaborone,English,-22.00,24.00,582000.0,Africa,Southern Africa,"['NAM', 'ZAF', 'ZMB', 'ZWE']",19,-0.4,1.90,1.10,23.10,-9.0,24.9,-7.3,2.52
130,Libya,Libyan dinar,Tripoli,Arabic,25.00,17.00,1759540.0,Africa,Northern Africa,"['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN']",47,17.3,3.00,1.70,18.60,8.5,83.0,18.5,7.38
137,Palestine,Egyptian pound,Ramallah,Arabic,31.90,35.20,6220.0,Asia,Western Asia,"['ISR', 'EGY', 'JOR']",14,9.1,-3.12,59.35,28.60,0.5,30.7,-21.1,5.61
143,Namibia,Namibian dollar,Windhoek,Afrikaans,-22.00,17.00,825615.0,Africa,Southern Africa,"['AGO', 'BWA', 'ZAF', 'ZMB']",13,3.8,6.75,3.50,19.10,-3.9,65.3,-15.3,2.69
162,Gabon,Central African CFA franc,Libreville,French,-1.00,11.75,267668.0,Africa,Middle Africa,"['CMR', 'COG', 'GNQ']",21,2.8,4.50,0.70,20.10,-3.0,73.4,5.1,2.54

# Ethiopia affront alot of unemployment achallenges

In [66]:
high_Jobless = df[(df["Jobless Rate"] > Upper1) & (df["Population"] > Upper)]
high_Jobless

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
100,Ethiopia,Ethiopian birr,Addis Ababa,Amharic,8.0,38.0,1104300.0,Africa,Eastern Africa,"['DJI', 'ERI', 'KEN', 'SOM', 'SSD', 'SDN']",164,6.5,15.0,13.7,18.9,-2.0,32.0,-3.4,132.06

In [69]:
Q3=373.000000
IQR=373.000000-20.000000
Upper3=373.000000 +1.5*IQR
Strong_country=df[df["GDP"]>Upper3]
Strong_country

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,1.8,4.50,2.70,4.20,-6.4,124.30,-3.90,341.15
6,United Kingdom,British pound,London,English,54.000000,-2.000000,242900.0,Europe,Northern Europe,['IRL'],3644,1.1,4.00,3.80,4.70,-4.8,95.90,-2.70,69.23
8,Poland,Polish złoty,Warsaw,Polish,52.000000,20.000000,312679.0,Europe,Central Europe,"['BLR', 'CZE', 'DEU', 'LTU', 'RUS', 'SVK', 'UKR']",915,3.2,5.00,3.10,5.20,-6.6,55.30,0.00,36.50
14,Russia,Russian ruble,Moscow,Russian,60.000000,100.000000,17098242.0,Europe,Eastern Europe,"['AZE', 'BLR', 'CHN', 'EST', 'FIN', 'GEO', 'KA...",2174,1.5,18.00,8.80,2.20,-1.7,16.40,2.90,146.20
27,Spain,Euro,Madrid,Spanish,40.000000,-4.000000,505992.0,Europe,Southern Europe,"['AND', 'FRA', 'GIB', 'PRT', 'MAR']",1723,2.5,2.15,2.70,10.29,-3.2,101.80,3.10,49.08
33,Turkey,Turkish lira,Ankara,Turkish,39.000000,35.000000,783562.0,Asia,Western Asia,"['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IR...",1323,2.7,43.00,33.52,8.60,-4.9,24.70,-0.80,85.67
49,India,Indian rupee,New Delhi,English,20.000000,77.000000,3287590.0,Asia,Southern Asia,"['BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK']",3913,7.8,5.50,1.55,5.20,-4.8,81.59,-0.60,1398.60
52,South Korea,South Korean won,Seoul,Korean,37.000000,127.500000,100210.0,Asia,Eastern Asia,['PRK'],1713,1.0,2.50,2.10,2.50,-3.9,46.80,5.30,51.75
71,Saudi Arabia,Saudi riyal,Riyadh,Arabic,25.000000,45.000000,2149690.0,Asia,Western Asia,"['IRQ', 'JOR', 'KWT', 'OMN', 'QAT', 'ARE', 'YEM']",1238,4.6,5.00,2.10,2.80,-2.8,29.90,5.90,35.30
79,Italy,Euro,Rome,Italian,42.833333,12.833333,301336.0,Europe,Southern Europe,"['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT']",2373,0.4,2.15,1.70,6.30,-3.4,135.30,1.10,58.93
86,Brazil,Brazilian real,Brasília,Portuguese,-10.000000,-55.000000,8515767.0,Americas,South America,"['ARG', 'BOL', 'COL', 'GUF', 'GUY', 'PRY', 'PE...",2179,2.7,15.00,5.23,5.80,-8.5,76.50,-2.55,212.58
91,Canada,Canadian dollar,Ottawa,English,60.000000,-95.000000,9984670.0,Americas,North America,['USA'],2241,1.4,2.75,1.70,6.90,-2.1,110.80,-1.00,41.53
94,Indonesia,Indonesian rupiah,Jakarta,Indonesian,-5.000000,120.000000,1904569.0,Asia,South-Eastern Asia,"['TLS', 'MYS', 'PNG']",1396,4.7,5.00,2.37,4.76,-2.3,38.80,-0.63,281.60
108,China,Chinese yuan,Beijing,Chinese,35.000000,105.000000,9706961.0,Asia,Eastern Asia,"['AFG', 'BTN', 'MMR', 'HKG', 'IND', 'KAZ', 'NP...",18744,4.0,3.00,0.00,5.20,-6.5,88.30,2.20,1408.00
124,Germany,Euro,Berlin,German,51.000000,9.000000,357114.0,Europe,Western Europe,"['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'LUX', 'NL...",4660,0.0,2.15,2.00,6.30,-2.8,62.50,5.70,83.60
141,France,Euro,Paris,French,46.000000,2.000000,551695.0,Europe,Western Europe,"['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ES...",3162,0.6,2.15,1.00,7.50,-5.8,113.00,0.40,68.44
144,Australia,Australian dollar,Canberra,English,-27.000000,133.000000,7692024.0,Oceania,Australia and New Zealand,NaN,1752,1.6,3.60,2.10,4.20,0.6,43.80,-2.10,27.40
150,Switzerland,Swiss franc,Bern,French,47.000000,8.000000,41284.0,Europe,Western Europe,"['AUT', 'FRA', 'ITA', 'LIE', 'DEU']",937,0.9,0.00,0.20,2.70,0.6,37.60,5.10,9.05
152,Japan,Japanese yen,Tokyo,Japanese,36.000000,138.000000,377930.0,Asia,Eastern Asia,NaN,4026,0.6,0.50,3.10,2.50,-2.3,236.70,4.70,120.65
153,Netherlands,Euro,Amsterdam,Dutch,52.500000,5.750000,41850.0,Europe,Western Europe,"['BEL', 'DEU']",1228,1.4,2.15,2.90,3.80,-1.1,43.70,9.10,18.04
167,Mexico,Mexican peso,Mexico City,Spanish,23.000000,-102.000000,1964375.0,Americas,North America,"['BLZ', 'GTM', 'USA']",1853,-0.3,7.75,3.51,2.70,-5.7,49.70,-0.80,130.86

In [67]:
df.describe()

,latitude,longitude,area,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
count,173.000000,173.000000,1.730000e+02,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000
mean,20.437142,22.371774,7.561437e+05,637.508671,3.328960,4.377977,8.331058,7.386994,-3.893584,1.657630,-17.832081,45.570058
std,23.961270,58.849734,2.007481e+06,2703.930867,3.242023,19.861826,21.306060,6.119770,11.237425,765.823809,131.150223,155.896870
min,-41.000000,-102.000000,2.020000e+00,2.000000,-5.000000,-100.000000,-9.100000,0.000000,-100.000000,-10000.000000,-1000.000000,0.040000
25%,6.500000,-2.000000,3.839400e+04,20.000000,1.800000,2.250000,1.300000,3.200000,-5.000000,35.000000,-5.300000,3.540000
50%,20.000000,24.000000,1.810350e+05,72.000000,2.800000,5.100000,3.400000,5.200000,-3.150000,54.320000,-1.000000,10.580000
75%,40.000000,49.000000,5.870410e+05,373.000000,4.400000,8.500000,5.300000,9.130000,-1.010000,74.180000,3.220000,34.430000
max,65.000000,178.065000,1.709824e+07,29185.000000,27.200000,59.230000,172.000000,33.200000,21.600000,272.000000,31.400000,1408.000000

In [70]:
Q3=4.400000
IQR=4.400000-1.800000
Upper4=4.400000 +1.5*IQR
Expanding_country=df[df["GDP Growth"]>Upper4]
Expanding_country

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
42,South Sudan,South Sudanese pound,Juba,English,7.0,30.0,619745.0,Africa,Middle Africa,"['CAF', 'COD', 'ETH', 'KEN', 'SDN', 'UGA']",12,27.2,12.00,112.60,12.5,-4.0,54.32,13.61,11.94
48,Guyana,Guyanese dollar,Georgetown,English,5.0,-59.0,214969.0,Americas,South America,"['BRA', 'SUR', 'VEN']",25,14.4,5.00,4.20,10.2,-7.4,24.30,24.60,0.78
83,Senegal,West African CFA franc,Dakar,French,14.0,-14.0,196722.0,Africa,Western Africa,"['GMB', 'GIN', 'GNB', 'MLI', 'MRT']",32,9.3,5.25,1.80,21.7,-11.7,56.10,-12.10,18.80
130,Libya,Libyan dinar,Tripoli,Arabic,25.0,17.0,1759540.0,Africa,Northern Africa,"['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN']",47,17.3,3.00,1.70,18.6,8.5,83.00,18.50,7.38
137,Palestine,Egyptian pound,Ramallah,Arabic,31.9,35.2,6220.0,Asia,Western Asia,"['ISR', 'EGY', 'JOR']",14,9.1,-3.12,59.35,28.6,0.5,30.70,-21.10,5.61

In [75]:
Q3=5.300000
IQR=5.300000-1.300000
Upper5=5.300000 +1.5*IQR
print(Upper5)
high_inflation=df[df["Inflation Rate"]>Upper5]
high_inflation

11.3

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
7,Myanmar,Burmese kyat,Naypyidaw,Burmese,22.000000,98.000000,676578.0,Asia,South-Eastern Asia,"['BGD', 'CHN', 'IND', 'LAO', 'THA']",74,1.9,9.00,28.58,3.0,-5.70,61.30,-5.50,54.50
11,Angola,Angolan kwanza,Luanda,Portuguese,-12.500000,18.500000,1246700.0,Africa,Middle Africa,"['COG', 'COD', 'ZMB', 'NAM']",80,2.4,19.50,19.48,29.4,-1.50,58.20,5.40,35.12
17,Sudan,Sudanese pound,Khartoum,Arabic,15.000000,30.000000,1886068.0,Africa,Northern Africa,"['CAF', 'TCD', 'EGY', 'ERI', 'ETH', 'LBY', 'SSD']",50,8.3,28.30,146.60,20.8,-3.20,272.00,-5.50,50.45
22,Burundi,Burundian franc,Gitega,French,-3.500000,30.000000,27834.0,Africa,Eastern Africa,"['COD', 'RWA', 'TZA']",2,1.9,12.00,41.60,0.9,-5.00,13.10,-8.50,14.05
30,Malawi,Malawian kwacha,Lilongwe,English,-13.500000,34.000000,118484.0,Africa,Eastern Africa,"['MOZ', 'TZA', 'ZMB']",11,3.5,26.00,27.30,5.0,-8.20,87.70,-19.50,20.30
33,Turkey,Turkish lira,Ankara,Turkish,39.000000,35.000000,783562.0,Asia,Western Asia,"['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IR...",1323,2.7,43.00,33.52,8.6,-4.90,24.70,-0.80,85.67
42,South Sudan,South Sudanese pound,Juba,English,7.000000,30.000000,619745.0,Africa,Middle Africa,"['CAF', 'COD', 'ETH', 'KEN', 'SDN', 'UGA']",12,27.2,12.00,112.60,12.5,-4.00,54.32,13.61,11.94
43,Iran,Iranian rial,Tehran,Persian (Farsi),32.000000,53.000000,1648195.0,Asia,Southern Asia,"['AFG', 'ARM', 'AZE', 'IRQ', 'PAK', 'TUR', 'TKM']",437,0.3,23.00,38.70,7.2,-5.50,36.80,2.90,86.00
61,Zimbabwe,Zimbabwean dollar,Harare,Chibarwe,-20.000000,30.000000,390757.0,Africa,Southern Africa,"['BWA', 'MOZ', 'ZAF', 'ZMB']",44,6.0,35.00,95.80,8.6,-1.20,87.00,1.30,15.18
62,Bolivia,Bolivian boliviano,Sucre,Aymara,-17.000000,-65.000000,1098581.0,Americas,South America,"['ARG', 'BRA', 'CHL', 'PRY', 'PER']",50,1.1,4.05,24.86,2.4,-7.80,95.00,-2.70,12.41
68,Cuba,Cuban convertible peso,Havana,Spanish,21.500000,-80.000000,109884.0,Americas,Caribbean,NaN,107,-1.9,2.25,14.37,1.5,-11.10,119.00,-0.50,9.75
81,Syria,Syrian pound,Damascus,Arabic,35.000000,38.000000,185180.0,Asia,Western Asia,"['IRQ', 'ISR', 'JOR', 'LBN', 'TUR']",20,1.3,-100.00,15.87,13.0,-11.40,30.01,-0.90,24.67
93,Kazakhstan,Kazakhstani tenge,Astana,Kazakh,48.019600,66.923700,2724900.0,Asia,Central Asia,"['CHN', 'KGZ', 'RUS', 'TKM', 'UZB']",288,4.9,16.50,11.80,4.6,-2.30,23.70,1.30,20.27
100,Ethiopia,Ethiopian birr,Addis Ababa,Amharic,8.000000,38.000000,1104300.0,Africa,Eastern Africa,"['DJI', 'ERI', 'KEN', 'SOM', 'SSD', 'SDN']",164,6.5,15.00,13.70,18.9,-2.00,32.00,-3.40,132.06
104,Nigeria,Nigerian naira,Abuja,English,10.000000,8.000000,923768.0,Africa,Western Africa,"['BEN', 'CMR', 'TCD', 'NER']",188,3.0,27.50,21.88,4.3,-6.10,52.90,-0.50,232.68
111,Ghana,Ghanaian cedi,Accra,English,8.000000,-2.000000,238533.0,Africa,Western Africa,"['BFA', 'CIV', 'TGO']",83,4.0,25.00,12.10,3.0,-4.80,70.50,4.40,34.43
117,Lebanon,Lebanese pound,Beirut,Arabic,33.833333,35.833333,10452.0,Asia,Western Asia,"['ISR', 'SYR']",20,-5.0,20.00,14.30,11.5,-0.40,164.10,-31.50,5.80
119,Zambia,Zambian kwacha,Lusaka,English,-15.000000,30.000000,752612.0,Africa,Eastern Africa,"['AGO', 'BWA', 'COD', 'MWI', 'MOZ', 'NAM', 'TZ...",26,6.6,14.50,13.00,12.0,-3.50,69.60,-1.00,19.70
120,Venezuela,Venezuelan bolívar soberano,Caracas,Spanish,8.000000,-66.000000,916445.0,Americas,South America,"['BRA', 'COL', 'GUY']",112,-4.0,59.23,172.00,5.5,-3.30,164.30,4.10,34.09
122,Ukraine,Ukrainian hryvnia,Kyiv,Ukrainian,49.000000,32.000000,603500.0,Europe,Eastern Europe,"['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK']",191,2.0,15.50,14.10,10.5,-17.60,89.80,-8.10,41.21
137,Palestine,Egyptian pound,Ramallah,Arabic,31.900000,35.200000,6220.0,Asia,Western Asia,"['ISR', 'EGY', 'JOR']",14,9.1,-3.12,59.35,28.6,0.50,30.70,-21.10,5.61
157,Haiti,Haitian gourde,Port-au-Prince,French,19.000000,-72.416667,27750.0,Americas,Caribbean,['DOM'],25,-1.0,17.00,29.60,15.1,7.10,14.00,-0.40,11.90
158,Argentina,Argentine peso,Buenos Aires,Guaraní,-34.000000,-64.000000,2780400.0,Americas,South America,"['BOL', 'BRA', 'CHL', 'PRY', 'URY']",633,5.5,29.00,36.60,7.9,-4.37,83.20,0.60,47.07
159,Egypt,Egyptian pound,Cairo,Arabic,27.000000,30.000000,1002450.0,Africa,Northern Africa,"['ISR', 'LBY', 'PSE', 'SDN']",389,3.8,24.00,13.90,6.1,-7.10,82.90,-5.30,107.20

# Strong economic,but with high prices

In [74]:
Strong_inflation=pd.merge(high_inflation,Strong_country,how="inner")
Strong_inflation

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Turkey,Turkish lira,Ankara,Turkish,39.0,35.0,783562.0,Asia,Western Asia,"['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IR...",1323,2.7,43.0,33.52,8.6,-4.9,24.7,-0.8,85.67

In [78]:
Q3=-1.010000		
IQR=-1.010000--5.000000
Upper6=-1.010000+1.5*IQR
print(Upper6)
high_budget=df[df["Gov. Budget"]>Upper6]
high_budget

4.9750000000000005

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
63,Lesotho,Lesotho loti,Maseru,English,-29.5,28.500000,30355.0,Africa,Southern Africa,['ZAF'],2,1.5,7.00,4.30,16.1,8.4,60.0,-0.4,2.34
66,Norway,Norwegian krone,Oslo,Norwegian Nynorsk,62.0,10.000000,323802.0,Europe,Northern Europe,"['FIN', 'SWE', 'RUS']",484,2.1,4.25,3.30,5.4,13.2,55.1,16.7,5.55
130,Libya,Libyan dinar,Tripoli,Arabic,25.0,17.000000,1759540.0,Africa,Northern Africa,"['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN']",47,17.3,3.00,1.70,18.6,8.5,83.0,18.5,7.38
157,Haiti,Haitian gourde,Port-au-Prince,French,19.0,-72.416667,27750.0,Americas,Caribbean,['DOM'],25,-1.0,17.00,29.60,15.1,7.1,14.0,-0.4,11.90
160,Kuwait,Kuwaiti dinar,Kuwait City,Arabic,29.5,45.750000,17818.0,Asia,Western Asia,"['IRQ', 'SAU']",160,1.9,4.00,2.39,2.1,21.6,3.0,28.2,4.79

# Libya is a progress country

In [80]:
GDP_Budget=pd.merge(high_budget,Expanding_country,how="inner")
GDP_Budget

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Libya,Libyan dinar,Tripoli,Arabic,25.0,17.0,1759540.0,Africa,Northern Africa,"['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN']",47,17.3,3.0,1.7,18.6,8.5,83.0,18.5,7.38

In [81]:
df.describe()

,latitude,longitude,area,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
count,173.000000,173.000000,1.730000e+02,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000,173.000000
mean,20.437142,22.371774,7.561437e+05,637.508671,3.328960,4.377977,8.331058,7.386994,-3.893584,1.657630,-17.832081,45.570058
std,23.961270,58.849734,2.007481e+06,2703.930867,3.242023,19.861826,21.306060,6.119770,11.237425,765.823809,131.150223,155.896870
min,-41.000000,-102.000000,2.020000e+00,2.000000,-5.000000,-100.000000,-9.100000,0.000000,-100.000000,-10000.000000,-1000.000000,0.040000
25%,6.500000,-2.000000,3.839400e+04,20.000000,1.800000,2.250000,1.300000,3.200000,-5.000000,35.000000,-5.300000,3.540000
50%,20.000000,24.000000,1.810350e+05,72.000000,2.800000,5.100000,3.400000,5.200000,-3.150000,54.320000,-1.000000,10.580000
75%,40.000000,49.000000,5.870410e+05,373.000000,4.400000,8.500000,5.300000,9.130000,-1.010000,74.180000,3.220000,34.430000
max,65.000000,178.065000,1.709824e+07,29185.000000,27.200000,59.230000,172.000000,33.200000,21.600000,272.000000,31.400000,1408.000000

In [86]:
Q3=8.500000		
IQR=8.500000- 2.250000
Upper7=-8.500000 +1.5*IQR
print(Upper7)
interest_rate=df[df["Interest Rate"]>Upper7]
high_budget

0.875

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,Tunisia,Tunisian dinar,Tunis,Arabic,34.000000,9.000000,163610.0,Africa,Northern Africa,"['DZA', 'LBY']",53,1.4,7.50,5.30,15.70,-6.6,79.8,-2.7,11.89
1,Vietnam,Vietnamese đồng,Hanoi,Vietnamese,16.166667,107.833333,331212.0,Asia,South-Eastern Asia,"['KHM', 'CHN', 'LAO']",476,6.1,4.50,3.19,2.24,-4.0,32.9,6.1,101.30
2,Ecuador,United States dollar,Quito,Spanish,-2.000000,-77.500000,276841.0,Americas,South America,"['COL', 'PER']",125,1.7,8.50,0.72,4.50,-1.9,50.6,2.8,17.97
3,Puerto Rico,United States dollar,San Juan,English,18.250000,-66.500000,8870.0,Americas,Caribbean,NaN,126,-0.8,6.60,1.20,5.70,-100.0,47.0,4.9,3.20
4,United States,United States dollar,"Washington, D.C.",English,38.000000,-97.000000,9372610.0,Americas,North America,"['CAN', 'MEX']",29185,1.8,4.50,2.70,4.20,-6.4,124.3,-3.9,341.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Mexico,Mexican peso,Mexico City,Spanish,23.000000,-102.000000,1964375.0,Americas,North America,"['BLZ', 'GTM', 'USA']",1853,-0.3,7.75,3.51,2.70,-5.7,49.7,-0.8,130.86
168,New Caledonia,CFP franc,Nouméa,French,-21.500000,165.500000,18575.0,Oceania,Melanesia,NaN,10,1.2,2.00,0.80,11.20,-0.1,0.0,-1000.0,0.29
169,Kosovo,Euro,Pristina,Albanian,42.666667,21.166667,10908.0,Europe,Southeast Europe,"['ALB', 'MKD', 'MNE', 'SRB']",11,4.0,2.90,4.30,10.80,0.2,16.9,-9.0,1.60
170,Malaysia,Malaysian ringgit,Kuala Lumpur,English,2.500000,112.500000,330803.0,Asia,South-Eastern Asia,"['BRN', 'IDN', 'THA']",422,4.1,2.75,1.20,3.00,-4.1,70.4,1.7,34.10
172,Jamaica,Jamaican dollar,Kingston,English,18.250000,-77.500000,10991.0,Americas,Caribbean,NaN,20,2.1,5.75,3.30,3.30,-1.0,67.9,1.3,2.82

# GDP Growth is high ,even the interset rate high

In [93]:
GDP_Growth_interest=pd.merge(interest_rate,Expanding_country,how="inner")
GDP_Growth_interest

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
0,South Sudan,South Sudanese pound,Juba,English,7.0,30.0,619745.0,Africa,Middle Africa,"['CAF', 'COD', 'ETH', 'KEN', 'SDN', 'UGA']",12,27.2,12.00,112.6,12.5,-4.0,54.32,13.61,11.94
1,Guyana,Guyanese dollar,Georgetown,English,5.0,-59.0,214969.0,Americas,South America,"['BRA', 'SUR', 'VEN']",25,14.4,5.00,4.2,10.2,-7.4,24.30,24.60,0.78
2,Senegal,West African CFA franc,Dakar,French,14.0,-14.0,196722.0,Africa,Western Africa,"['GMB', 'GIN', 'GNB', 'MLI', 'MRT']",32,9.3,5.25,1.8,21.7,-11.7,56.10,-12.10,18.80
3,Libya,Libyan dinar,Tripoli,Arabic,25.0,17.0,1759540.0,Africa,Northern Africa,"['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN']",47,17.3,3.00,1.7,18.6,8.5,83.00,18.50,7.38

# lossing country

In [91]:
Q3=74.180000	
IQR=74.180000- 35.000000
Upper8=74.180000 +1.5*IQR
print(Upper8)
Dept_GDP=df[df["Debt/GDP"]>Upper8]
Dept_GDP

132.95000000000002

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
17,Sudan,Sudanese pound,Khartoum,Arabic,15.000000,30.000000,1886068.0,Africa,Northern Africa,"['CAF', 'TCD', 'EGY', 'ERI', 'ETH', 'LBY', 'SSD']",50,8.3,28.30,146.6,20.8,-3.2,272.0,-5.5,50.45
38,Greece,Euro,Athens,Greek,39.000000,22.000000,131990.0,Europe,Southern Europe,"['ALB', 'BGR', 'TUR', 'MKD']",257,2.0,2.15,3.1,7.9,1.3,153.6,-6.4,10.41
79,Italy,Euro,Rome,Italian,42.833333,12.833333,301336.0,Europe,Southern Europe,"['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT']",2373,0.4,2.15,1.7,6.3,-3.4,135.3,1.1,58.93
109,Singapore,Singapore dollar,Singapore,English,1.366667,103.800000,710.0,Asia,South-Eastern Asia,MYS,547,2.0,1.51,0.8,2.1,-1.6,173.1,17.5,6.04
117,Lebanon,Lebanese pound,Beirut,Arabic,33.833333,35.833333,10452.0,Asia,Western Asia,"['ISR', 'SYR']",20,-5.0,20.00,14.3,11.5,-0.4,164.1,-31.5,5.80
120,Venezuela,Venezuelan bolívar soberano,Caracas,Spanish,8.000000,-66.000000,916445.0,Americas,South America,"['BRA', 'COL', 'GUY']",112,-4.0,59.23,172.0,5.5,-3.3,164.3,4.1,34.09
125,Eritrea,Eritrean nakfa,Asmara,Arabic,15.000000,39.000000,117600.0,Africa,Eastern Africa,"['DJI', 'ETH', 'SDN']",2,2.8,-100.00,9.0,5.6,-3.4,164.0,12.4,3.21
139,Bahrain,Bahraini dinar,Manama,Arabic,26.000000,50.550000,765.0,Asia,Western Asia,NaN,48,2.8,5.25,-0.4,6.3,-5.6,134.0,5.3,1.59
152,Japan,Japanese yen,Tokyo,Japanese,36.000000,138.000000,377930.0,Asia,Eastern Asia,NaN,4026,0.6,0.50,3.1,2.5,-2.3,236.7,4.7,120.65

# exporting more than importing

In [92]:
Q3=3.220000		
IQR=3.220000--5.300000
Upper8=3.220000	+1.5*IQR
print(Upper8)
Current_account=df[df["Current Account"]>Upper8]
Current_account

16.0

,name,currency,capital,languages,latitude,longitude,area,region,subregion,borders,GDP,GDP Growth,Interest Rate,Inflation Rate,Jobless Rate,Gov. Budget,Debt/GDP,Current Account,Population
48,Guyana,Guyanese dollar,Georgetown,English,5.000000,-59.00,214969.0,Americas,South America,"['BRA', 'SUR', 'VEN']",25,14.4,5.00,4.20,10.2,-7.4,24.3,24.6,0.78
66,Norway,Norwegian krone,Oslo,Norwegian Nynorsk,62.000000,10.00,323802.0,Europe,Northern Europe,"['FIN', 'SWE', 'RUS']",484,2.1,4.25,3.30,5.4,13.2,55.1,16.7,5.55
109,Singapore,Singapore dollar,Singapore,English,1.366667,103.80,710.0,Asia,South-Eastern Asia,MYS,547,2.0,1.51,0.80,2.1,-1.6,173.1,17.5,6.04
127,Papua New Guinea,Papua New Guinean kina,Port Moresby,English,-6.000000,147.00,462840.0,Oceania,Melanesia,['IDN'],33,4.6,4.00,5.28,2.7,-4.4,51.1,17.4,10.58
130,Libya,Libyan dinar,Tripoli,Arabic,25.000000,17.00,1759540.0,Africa,Northern Africa,"['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN']",47,17.3,3.00,1.70,18.6,8.5,83.0,18.5,7.38
131,Qatar,Qatari riyal,Doha,Arabic,25.500000,51.25,11586.0,Asia,Western Asia,['SAU'],218,2.4,5.10,-0.08,0.1,0.7,40.8,17.4,3.12
146,Ireland,Euro,Dublin,English,53.000000,-8.00,70273.0,Europe,Northern Europe,['GBR'],577,2.3,2.15,1.70,4.9,4.3,40.9,17.2,5.44
160,Kuwait,Kuwaiti dinar,Kuwait City,Arabic,29.500000,45.75,17818.0,Asia,Western Asia,"['IRQ', 'SAU']",160,1.9,4.00,2.39,2.1,21.6,3.0,28.2,4.79
166,Macau,Macanese pataca,No Capital,Portuguese,22.166667,113.55,30.0,Asia,Eastern Asia,['CHN'],50,5.1,4.75,0.12,1.9,-1.0,0.0,31.4,0.69

In [ ]:
with pd.ExcelWriter('World econimics.xlsx') as writer:
    Strong_country.to_excel(writer, sheet_name="main",index=False)
    Expanding_country.to_excel(writer, sheet_name="main2",index=False)
    interest_rate.to_excel(writer, sheet_name="main3",index=False)
    Current_account.to_excel(writer, sheet_name="main4",index=False)
    Dept_GDP.to_excel(writer, sheet_name="main5",index=False)
    GDP_Growth_interest.to_excel(writer, sheet_name="main6",index=False)
    high_budget.to_excel(writer, sheet_name="main7",index=False)
    high_inflation.to_excel(writer, sheet_name="main8",index=False)
    Jobless.to_excel(writer, sheet_name="main9",index=False)
    high_population.to_excel(writer, sheet_name="main10",index=False)

#### in this dataset Monaco is most frequent country having missing value and there no reilable source to bring the value required
#### and for obtaining the missing ,i used Wikipedia by using scrap